version: 3
jobs:
  build:
    steps:
    
	  - checkout
	  
	  - restore_cache:
          key: robindrew-common-{{ checksum "pom.xml" }}
      
	  - run: mvn dependency:go-offline
	  
	  - save_cache:
          paths:
            - ~/.m2
          key: robindrew-common-{{ checksum "pom.xml" }}
	  
	  - run: mvn package
	  
	  - store_artifacts:
          path: target/robindrew-common-0.0.1-SNAPSHOT.jar
